{{- if .Values.integrations.ossm.create -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echoapi-vs
  namespace: demo
spec:
  hosts:
  - "echo.s9lk8.azure.redhatworkshops.io"
  gateways:
  - custom-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: echoapi
        port:
          number: 9292
{{- end -}}