# {{- if .Values.integrations.certmgr.enabled -}}
# apiVersion: operator.openshift.io/v1
# kind: IngressController
# metadata:    
    # annotations:
    #   argocd.argoproj.io/sync-wave: "4"
#   name: custom
#   namespace: openshift-ingress-operator
# spec:
#   domain: {{ .Values.integrations.certmgr.dnszone_name }}
#   nodePlacement:
#     nodeSelector:
#       matchLabels:
#         node-role.kubernetes.io/worker: ""
#   routeSelector:
#     matchLabels:
#       type: custom
#   defaultCertificate:
#     name: tls-cert
#   httpEmptyRequestsPolicy: Respond
#   replicas: 3
# {{- end -}}
