{{- if .Values.integrations.certmgr.enabled -}}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ .Values.integrations.certmgr.dnszone_secret_name }}-external-secret
  namespace: openshift-cert-manager
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{  .Values.integrations.eso.clustersecretstore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.integrations.certmgr.dnszone_secret_name }}
  data:
  - secretKey: client-secret
    remoteRef:
      key: secret/{{ .Values.integrations.certmgr.dnszone_secret_key }}
{{- end -}}