---
{{- if .Values.autoscaler.enabled }}
{{- range $key, $value := .Values.autoscaler.machineset }}
apiVersion: "autoscaling.openshift.io/v1beta1"
kind: "MachineAutoscaler"
metadata:
  name: {{ .name }}-autoscaler 
  namespace: "openshift-machine-api"
spec:
  minReplicas: 2 #1 
  maxReplicas: 12 
  scaleTargetRef: 
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet 
    name: {{ .name }}
---
{{- end }}
{{- end}}