
## Cluster Secrets by Environments

cluster_sp_id_key: clientIdOne
cluster_sp_secret_key: clientSecretOne
cluster_tenant_id_key: tenantId
cluster_subscription_id_key: subId
cluster_sp_object_id_key: spObjectId
pull_secret_akv_key: pullSecret
installer_clientid: ID #AccntclientId # 
installer_clientsecret: SECRET # AccntclientSecret  # 
imageRegistryHostnameKey: acrName
imageRegistryUsernameKey: acrUsername
imageRegistryPasswordKey: acrPassword
masEntitlementKey: masEntitlement
masLicenseIdKey: masLicenseId
masLicenseKey: masLicense

## Cluster Tags. Max of 10 tags
tags: 
  - key: createdBy 
    value: "test-user" 
  - key: purpose
    value: "test-cluster"
  - key: tag3
    value: value3
  - key: tag4
    value: value4
  - key: tag5
    value: value5
  - key: tag6
    value: value6
  - key: tag7
    value: value7
  - key: tag8
    value: value8
  - key: tag9
    value: value9
  - key: tag10
    value: value10

## Parameters if needed to create Network Resources Values
vnet:
  name: mas-aro-vnet
  location: eastus
  network_rg: mas-aro-vnet-rg
  address_cidr: 10.0.0.0/22
  control_plane: 
    name: mas-aro-cluster-control-subnet
    address_cidr: 10.0.0.0/23
  worker_plane:
    name: mas-aro-cluster-worker-subnet
    address_cidr: 10.0.2.0/23

# outbound-type: Loadbalancer|UserDefinedRouting
cluster:
  conditionals:
    create_network_vnet_and_subnets: true
    specify_custom_domain: True
    specify_version: True
    specify_disk_encryption_set: False
    specify_tags: True
    encrypt_master_hosts: False
    encrypt_worker_hosts: False
    enable_preconfigured_nsg: False
    create_azure_policy_for_tags: True
    enable_fips: False
    use_aro_sp: True
    use_installer_sp: true
    create_cluster_resource_group: true
    assign_rbac_roles: true
  name: mas-aro-cluster
  cluster_resource_group:  placeholderrg   
  location: eastus
  domain: odf1
  policy_definition: aro-policy-def
  version: "4.14.16"
  control_instance: Standard_D8s_v3
  worker_disk: 128
  worker_node_count: 3 
  worker_instance: Standard_D16s_v3 #Standard_D4s_v3 
  disk_encryption_set: ""
  network:
    vnet_name: aro-vnet-m00o63yq
    control_subnet_name: master-subnet
    worker_subnet_name: worker-subnet
    vnet_rg: aro-main
    outbound_type: Loadbalancer  
    ingress_visibility: Public 
    api_visibility: Public
    pod_cidr: 10.128.0.0/14
    service_cidr: 172.32.0.0/16  

integrations:
  gitops:
    add: true
    version: "gitops-1.11"
  eso:
    add: true
    clustersecretstore: akv-cluster-secret-read
    akvtenantid: 64dc69e4-d083-49fc-9569-ebece1dd1408
    vaultname: dd-aro-cluster-akv
    esoreadsecret: akv-sp-read
    esoreadsecretns: openshift-operators
  entraid:
    add: true
    clientid: ac52d2dd-b725-4009-b432-6be1fcbe2263
    secretname: entraid-idp-auth-secret
    tenantid: d84589ac-9d9c-44f1-a311-ff102f6f8b4e
    secretKeyinAKV: entraidSecret
  insights:
    enabled: true
  extendedlogging:
    enabled: true
  userworkloadmonitoring:
    enabled: true
  logforwarder:
    enabled: true
    azuremonitor:
      workspaceid: masworkspaceid
      secretname: mas-azure-monitor-shared-key
      akvname: azureMonitorSharedKey
  imagemirror:
    enabled: true
  imageregistry:
    add: true
    secretname: mas-registry-secret-name
    email: mymail@mail.com

storageaccount:
  name: masclusterstorageaccount
  resourcegroup: masstorageaccountrg
  location: eastus
  kind: FileStorage
  sku: Premium_LRS
  accesstier: Hot
  min_tls_version: "TLS1_2"
  publicaccess: "Enabled"
  privendpointname: masstorageaccountpe
  block:
    create: true
    sku: Premium_LRS
    sc_name: managed-premium
  file:
    create: true
    sku: Premium_LRS
    sc_name: azurefiles-premium
    secretname: sakey-secret
    nfs_sharename: masfileshare

imagemirror:
  - source: ghcr.io/external-secrets10/external-secrets
    mirror: 
      - acr.com/external-secrets10/external-secrets
  - source: ghcr.io/grafana/grafana-operator10
    mirror: 
      - acr.com/grafana10/grafana-operator10

autoscaler:
  enabled: false
  max_node_count: 9
  min_aggregate_cpu: 48
  max_aggregate_cpu: 144
  min_aggregate_memory: 192
  max_aggregate_memory: 576
  min_replica_per_az: 1
  max_replica_per_az: 3

  machineset:
    - mas-aro-cluster-sjv44-worker-eastus1
    - mas-aro-cluster-sjv44-worker-eastus2
    - mas-aro-cluster-sjv44-worker-eastus3

## MAS Variable
mas:
  prepare_install: true
  instance_id: mas1
  config_dir: $PWD/ansible/artefacts
  ansible_license_path: $PWD/artefacts/license.dat
  mas_license_path: $PWD/ansible/artefacts/license.dat
  dro_email: fanyaegb@redhat.com
  dro_firstname: Francis
  dro_lastname: Anyaegbu
  prometheus_alert_storageclass: managed-csi
  prometheus_storageclass: azurefiles-premium
  prometheus_user_storageclass: azurefiles-premium
  grafana_storageclass: azurefiles-premium
  mongodb_storageclass: azurefiles-premium
  uds_storageclass: azurefiles-premium



