{{- if .Values.integrations.ossm.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-distributed-tracing
{{- end }}
---
{{- if .Values.integrations.certmgr.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "cert-manager Operator for Red Hat OpenShift"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: cert-manager-operator
{{- end }}