{{- if .Values.integrations.ossm.create -}}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-distributed-tracing
  namespace: openshift-distributed-tracing
spec: {}
{{- end }}
