---
- name: Delete OpenShift Cluster & Environment
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - variables/test_var.yaml
    - variables/common_var.yaml


  roles:
    - delete-aro-cluster
