apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: logging-loki 
  namespace: openshift-logging 
spec:
  size: 1x.medium
  storage:
    schemas:
    - version: v12
      effectiveDate: "2022-06-01"
    secret:
      name: logging-loki-s3 
      type: s3 
      credentialMode: 
  storageClassName: azurefiles-premium
  tenants:
    mode: openshift-logging 