{{- if .Values.integrations.ossm.create -}}
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: default
  namespace: istio-system
spec:
  members:
    # - demo
    - test
{{- end -}}