# {{- range $key, $value := .Values.operators }}
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-wave: "0"
#   name: {{ .name }}-subscription
#   namespace: {{ .namespace }}
# spec:
#   channel: {{ .channnel }} 
#   installPlanApproval: {{ .installPlanApproval }}
#   name: {{ .operatorName }} 
#   source: {{ .source }} 
#   sourceNamespace: {{ .sourceNamespace }}
# ---
# {{- end }}

{{- range $key, $value := .Values.operators }}
{{- $shouldCreate := false }}

{{- if eq $value.name "servicemeshoperator" }}
  {{- $shouldCreate = $.Values.integrations.ossm.create }}
{{- end }}

{{- if eq $value.name "kiali-ossm" }}
  {{- $shouldCreate = $.Values.integrations.ossm.create }}
{{- end }}

{{- if eq $value.name "elasticsearch-operator" }}
  {{- $shouldCreate = $.Values.integrations.ossm.create }}
{{- end }}

{{- if eq $value.name "jaeger-product" }}
  {{- $shouldCreate = $.Values.integrations.ossm.create }}
{{- end }}

{{- if eq $value.name "external-secrets-operator" }}
  {{- $shouldCreate = $.Values.integrations.eso.add }}
{{- end }}

{{- if eq $value.name "openshift-cert-manager-operator" }}
  {{- $shouldCreate = $.Values.integrations.certmgr.enabled }}
{{- end }}

{{- if or (eq $shouldCreate true) (not $shouldCreate) }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ $value.sync_wave }}
  name: {{ $value.name }}-subscription
  namespace: {{ $value.namespace }}
spec:
  channel: {{ $value.channel }}
  installPlanApproval: {{ $value.installPlanApproval }}
  name: {{ $value.operatorName }}
  source: {{ $value.source }}
  sourceNamespace: {{ $value.sourceNamespace }}
---
{{- end }}
{{- end }}

